# This configuration lets you deploy the DynaDo backend on AWS Lambda
# using the serverless framework (https://www.serverless.com/framework/docs/).
#
# To retrieve all needed credentials, please follow the AWS wizard
# in 'Deploy Dynatrace'.

service: aws-lambda-todolist-service

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  memorySize: 128
  logRetentionInDays: 30

  apiGateway:
    shouldStartNameWithService: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource:
        Fn::Join:
          - ':'
          -
            - 'arn:aws:dynamodb'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'table/to-do-list-item'

plugins:
  - serverless-offline
  - serverless-api-gateway-throttling

resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}

functions:
  createTodo:
    name: createTodoListItem
    handler: handler.createItem
    layers: ${self:custom.layers}
    environment: ${self:custom.environment}
    events:
      - http:
          method: post
          path: todolist
          cors: ${self:custom.cors}

  updateTodo:
    name: updateTodoListItem
    handler: handler.updateItem
    layers: ${self:custom.layers}
    environment: ${self:custom.environment}
    events:
      - http:
          method: put
          path: todolist/{id}
          cors: ${self:custom.cors}

  deleteTodo:
    name: deleteTodoListItem
    handler: handler.deleteItem
    layers: ${self:custom.layers}
    environment: ${self:custom.environment}
    events:
      - http:
          method: delete
          path: todolist/{id}
          cors: ${self:custom.cors}

  getTodo:
    name: getTodoListItem
    handler: handler.getItem
    layers: ${self:custom.layers}
    environment: ${self:custom.environment}
    events:
      - http:
          method: get
          path: todolist/{id}
          cors: ${self:custom.cors}

  getTodos:
    name: getTodoListItems
    handler: handler.getItems
    layers: ${self:custom.layers}
    environment: ${self:custom.environment}
    events:
      - http:
          method: get
          path: todolist
          cors: ${self:custom.cors}

custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 5
    maxConcurrentRequests: 2

  dynamodb:
    stages:
      - dev

  # shared CORS settings for API Gateway
  cors:
    origin: '*' # <-- Specify allowed origin
    headers: # <-- Specify allowed headers
      - Content-Type
      - x-dtc
    allowCredentials: true

  layers: []

  environment:
    DUMMY_AS_ENVIRONMENT_MUST_NOT_BE_EMPTY: 1
